"""inject-cohesion.py — single-source-of-truth cohesion-layer injector for callmeie.ie.

Walks every *.html under repo root (excluding _partials/, scripts/, node_modules/, .git/).
For each sentinel pair, reads matching partial, substitutes {{tokens}} from sentinel
attributes, replaces region in-place. Idempotent.

USAGE:
  python scripts/inject-cohesion.py            # roll partials forward into all pages
  python scripts/inject-cohesion.py --check    # exit 1 if any page has drifted (CI / pre-commit)
  python scripts/inject-cohesion.py --page <path>  # operate on one page only

SENTINEL CONVENTION (see _partials/README.md):
  <!-- COHESION:STRIP-START -->
  <!-- COHESION:STRIP-END -->

  <!-- COHESION:STRIP-START variant=pill -->
  <!-- COHESION:STRIP-END -->

  <!-- COHESION:BREADCRUMB-START section="Receptionist" section_url="/receptionist/" page="Dental" -->
  <!-- COHESION:BREADCRUMB-END -->

  <!-- COHESION:FOOTER-START -->
  <!-- COHESION:FOOTER-END -->

PARTIAL FILE LOOKUP:
  STRIP (default)         -> _partials/cohesion-strip.html
  STRIP variant=pill      -> _partials/cohesion-strip-pill.html
  BREADCRUMB (default)    -> _partials/cohesion-breadcrumb.html
  FOOTER (default)        -> _partials/cohesion-footer.html
  FOOTER variant=demo     -> _partials/cohesion-footer-demo.html

EXIT CODES:
  0  -- all pages clean (or --check passed)
  1  -- drift detected (--check) OR partial-load error
  2  -- usage error / bad sentinel syntax
"""
from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PARTIALS_DIR = REPO_ROOT / "_partials"
EXCLUDE_DIRS = {"_partials", "scripts", "node_modules", ".git", ".github"}

# Sentinel regex captures: type, optional attrs blob, content, end-type
# Tolerates whitespace + newlines between the markers.
SENTINEL_RE = re.compile(
    r"<!--\s*COHESION:(?P<type>STRIP|BREADCRUMB|FOOTER|TRUST)-START(?P<attrs>[^>]*)-->"
    r"(?P<content>.*?)"
    r"<!--\s*COHESION:(?P=type)-END\s*-->",
    re.DOTALL | re.IGNORECASE,
)

# Stylesheet link to inject into <head> when sentinels present
COHESION_STYLE_LINK = '<link rel="stylesheet" href="/_partials/cohesion.css">'
COHESION_STYLE_MARKER = "/_partials/cohesion.css"

# Attribute parser: key="value" or key=value (no quotes, no spaces in value).
ATTR_RE = re.compile(r'(\w+)\s*=\s*(?:"([^"]*)"|(\S+))')


def parse_attrs(blob: str) -> dict[str, str]:
    """Parse attribute string from sentinel into dict. Empty blob -> empty dict."""
    return {m.group(1): (m.group(2) if m.group(2) is not None else m.group(3)) for m in ATTR_RE.finditer(blob)}


def lookup_partial(sentinel_type: str, attrs: dict[str, str]) -> Path:
    """Map (type, attrs) -> partial file path."""
    base = sentinel_type.lower()
    variant = attrs.get("variant", "").strip().lower()
    candidate = PARTIALS_DIR / f"cohesion-{base}{'-' + variant if variant else ''}.html"
    if not candidate.is_file():
        raise FileNotFoundError(f"Missing partial: {candidate.relative_to(REPO_ROOT)}")
    return candidate


def render_partial(partial_path: Path, attrs: dict[str, str]) -> str:
    """Read partial + substitute {{token}} placeholders from attrs. Unmatched tokens left as-is so drift detector can flag."""
    content = partial_path.read_text(encoding="utf-8")
    for key, value in attrs.items():
        content = content.replace("{{" + key + "}}", value)
    return content


def inject_one(page_path: Path) -> tuple[str, bool]:
    """Inject all sentinels in one page. Returns (new_content, changed)."""
    raw = page_path.read_text(encoding="utf-8")
    new_chunks: list[str] = []
    cursor = 0
    found_any = False

    for match in SENTINEL_RE.finditer(raw):
        found_any = True
        new_chunks.append(raw[cursor:match.start()])
        sentinel_type = match.group("type").upper()
        attrs = parse_attrs(match.group("attrs") or "")
        partial_path = lookup_partial(sentinel_type, attrs)
        rendered = render_partial(partial_path, attrs)
        # Wrap rendered content with the same sentinels so re-runs are idempotent.
        attrs_blob = (" " + " ".join(f'{k}="{v}"' for k, v in attrs.items())) if attrs else ""
        new_chunks.append(
            f"<!-- COHESION:{sentinel_type}-START{attrs_blob} -->\n"
            f"<!-- (auto-generated by scripts/inject-cohesion.py — DO NOT EDIT) -->\n"
            f"{rendered.rstrip()}\n"
            f"<!-- COHESION:{sentinel_type}-END -->"
        )
        cursor = match.end()

    new_chunks.append(raw[cursor:])
    new_content = "".join(new_chunks)

    if not found_any:
        return raw, False

    # Inject cohesion.css link into <head> if sentinels present and link missing.
    if COHESION_STYLE_MARKER not in new_content:
        # Insert just before </head> — falls back to inserting after <head> if </head> not found.
        if "</head>" in new_content:
            new_content = new_content.replace("</head>", f"  {COHESION_STYLE_LINK}\n</head>", 1)
        elif "<head>" in new_content:
            new_content = new_content.replace("<head>", f"<head>\n  {COHESION_STYLE_LINK}", 1)

    return new_content, new_content != raw


def find_pages() -> list[Path]:
    """All *.html under repo root, excluding EXCLUDE_DIRS."""
    pages: list[Path] = []
    for path in REPO_ROOT.rglob("*.html"):
        if any(part in EXCLUDE_DIRS for part in path.relative_to(REPO_ROOT).parts):
            continue
        pages.append(path)
    return pages


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="dry-run; exit 1 if any drift")
    parser.add_argument("--page", type=Path, help="operate on one page only (relative or absolute)")
    parser.add_argument("--verbose", "-v", action="store_true", help="print all pages, not just changed")
    args = parser.parse_args()

    if args.page:
        page = args.page if args.page.is_absolute() else REPO_ROOT / args.page
        if not page.is_file():
            print(f"ERR: page not found: {page}", file=sys.stderr)
            return 2
        pages = [page]
    else:
        pages = find_pages()

    drift_count = 0
    sentinel_count = 0
    skipped = 0
    error_count = 0

    for page in pages:
        rel = page.relative_to(REPO_ROOT).as_posix()
        try:
            new_content, changed = inject_one(page)
        except FileNotFoundError as e:
            print(f"  ERR  {rel}: {e}", file=sys.stderr)
            error_count += 1
            continue

        # Track if the page even contains sentinels (vs. a static page with no cohesion participation).
        has_sentinels = bool(SENTINEL_RE.search(page.read_text(encoding="utf-8")))
        if not has_sentinels:
            skipped += 1
            if args.verbose:
                print(f"  --   {rel} (no sentinels)")
            continue

        sentinel_count += 1

        if changed:
            drift_count += 1
            if args.check:
                print(f"  DRIFT  {rel}", file=sys.stderr)
            else:
                page.write_text(new_content, encoding="utf-8", newline="\n")
                print(f"  WROTE  {rel}")
        elif args.verbose:
            print(f"  OK     {rel}")

    summary = f"\n{'CHECK' if args.check else 'INJECT'} summary: {sentinel_count} pages with sentinels, {drift_count} drifted, {skipped} skipped, {error_count} errors"
    print(summary, file=sys.stderr if (drift_count and args.check) or error_count else sys.stdout)

    if error_count:
        return 1
    if args.check and drift_count:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
